version: "3.8"

services:
  gradio_app:
    build:
      context: .  # Use the root as context
      dockerfile: .docker/Dockerfile  # Specify the Dockerfile inside .docker
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
