name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cd ${{ secrets.DO_DEPLOY_PATH }}
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
